apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
  labels:
  namespace: homework
spec:
  containers:
  - name: server
    image: python:3.10.20-alpine3.22
    workingDir: /homework
    command: ["python3", "-m", "http.server", "8000"]
    volumeMounts:
    - name: workdir
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm /homework/index.html", "-f"]
  initContainers:
  - name: install
    image: busybox:1.28
    command:
      - wget
      - "-O"
      - "/init/index.html"
      - http://example.com
    volumeMounts:
    - name: workdir
      mountPath: /init
  volumes:
  - name: workdir
    emptyDir: {}
