apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: webserver-pvc
spec:
    storageClassName: manual-storage
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 50Mi
    selector:
      matchLabels:
        app: homework

